spring.application.name=Inventario
server.port=

spring.datasource.url=jdbc:postgresql://
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
